on: [push, pull_request]

name: Rust

env:
  RUSTFLAGS: -D warnings
  RUSTDOCFLAGS: -D warnings

jobs:
  fmt-crank-check-test:
    name: Format + check
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.81.0

      - name: Install packages (Linux)
        if: runner.os == 'Linux'
        uses: awalsh128/cache-apt-pkgs-action@v1.4.3
        with:
          packages: libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libxkbcommon-dev libssl-dev libgtk-3-dev # libgtk-3-dev is used by rfd
          version: 1.0
          execute_install_scripts: true

      - name: Set up cargo cache
        uses: Swatinem/rust-cache@v2

      - name: Rustfmt
        run: cargo fmt --all -- --check

      - name: check --all-features
        run: cargo check --locked --all-features --all-targets

      - name: check egui_extras --all-features
        run: cargo check --locked --all-features -p egui_extras

      - name: check default features
        run: cargo check --locked --all-targets

      - name: check --no-default-features
        run: cargo check --locked --no-default-features --lib --all-targets

      - name: check eframe --no-default-features
        run: cargo check --locked --no-default-features --features x11 --lib -p eframe

      - name: check egui_extras --no-default-features
        run: cargo check --locked --no-default-features --lib -p egui_extras

      - name: check epaint --no-default-features
        run: cargo check --locked --no-default-features --lib -p epaint

      # Regression test for https://github.com/emilk/egui/issues/4771
      - name: cargo check -p test_egui_extras_compilation
        run: cargo check -p test_egui_extras_compilation

      - name: cargo doc --document-private-items
        run: cargo doc --document-private-items --no-deps --all-features

      - name: clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: clippy release
        run: cargo clippy --all-targets --all-features --release -- -D warnings

  # ---------------------------------------------------------------------------

  windows:
    name: Check Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.81.0

      - name: Set up cargo cache
        uses: Swatinem/rust-cache@v2

      - name: Check all
        run: cargo check --all-targets --all-features

  # ---------------------------------------------------------------------------

  tests:
    name: Run tests
    # We run the tests on macOS because it will run with an actual GPU
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.81.0

      - name: Set up cargo cache
        uses: Swatinem/rust-cache@v2

      - name: Run tests
        run: cargo test --all-features