on: [push, pull_request]

name: Rust

env:
  RUSTFLAGS: -D warnings
  RUSTDOCFLAGS: -D warnings

jobs:
  windows-check-all:
    name: Check Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.84.1

      - name: Set up cargo cache
        uses: Swatinem/rust-cache@v2

      - name: install fmt
        run: rustup component add rustfmt

      - name: install clippy
        run: rustup component add clippy

      - name: Rustfmt
        run: cargo fmt --all -- --check

      - name: Check all
        run: cargo check --all-targets --all-features
      
      - name: Run tests
        run: cargo test --all-features

      - name: Run clippy
        run: cargo clippy --all-targets --all-features
